### ISSUE TITLE
Gallery3 Exif GPS

### ISSUE THREAD

**Issue by marisana** [rWatcher/rwatcher.github.com#1]
Hello rwatcher!
OK, Gallery3 is in hibernation over few years, but many users are continue to use it. Look at the Gallery3 Yahoo Group: https://groups.yahoo.com/neo/groups/gallery3/info
Gallery3 is still the best.

There is a problem with nonexistent Exif GPS album sites.
/exif_gps/map/album/1234
If a page is called up whose associated album no longer exists, then the server is running hot. 100% CPU and after a few minutes abort because the memory is full. This happens especially with searchrobots.

**Comment by rWatcher** [comment]
Dear marisana,

The email sent to rwatcher@watcherdatabase.tk with subject
"[rWatcher/rwatcher.github.com] Gallery3 Exif GPS (#1)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to rwatcher@watcherdatabase.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by rWatcher** [comment]
https://github.com/rWatcher/gallery3-contrib/commit/ea95544702139d71a6bc755d3e582eb9f5c4edbb
